LogFormat "%{%s}t.%{msec_frac}t %h %l %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" \"%{trace}C\" %D" idor

CustomLog logs/idor_apache.log idor

ProxyPreserveHost On
ProxyPass        / http://host.docker.internal:3001/
ProxyPassReverse / http://host.docker.internal:3001/
